microservice-chart:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-nodo-verifyko-aux
    tag: "0.2.9"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.nodo.internal.uat.platform.pagopa.it"
    path: /pagopa-nodo-verifyko-aux(/|$)(.*)
    servicePort: 8080
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "640Mi"
      cpu: "0.40"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopanodoverifykoaux' # required to show cloud role name in application insights
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-nodo-verifyko-aux"
    ENV: 'uat'
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    CACHE_ENABLED: 'true'
    VERIFYKO_COLDSTORAGE_TABLE: 'events'
    VERIFYKO_COLDSTORAGE_BLOBCONTAINER: 'payload'
    VERIFYKO_HOTSTORAGE_URI: 'https://pagopa-u-weu-nodo-verifyko-cosmos-account.documents.azure.com:443/'
    VERIFYKO_HOTSTORAGE_DATABASE: 'nodo_verifyko'
    VERIFYKO_HOTSTORAGE_ENABLEQUERYMETRICS: 'false'
    VERIFYKO_REPORT_MINUTESTIMEFRAME: '1440'
    OTEL_SERVICE_NAME: "pagopa-nodo-verifyko-aux"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  secretProvider:
    create: true
    envSecrets:
      # required
      APPLICATIONINSIGHTS_CONNECTION_STRING: "azure-insight-connection-string"
      OTEL_EXPORTER_OTLP_HEADERS: "elastic-apm-secret-token"
      VERIFYKO_COLDSTORAGE_CONNECTION: "verifyko-tablestorage-connection-string"
      VERIFYKO_HOTSTORAGE_KEY: "verifyko-datastore-primary-key"
    keyvault:
      name: "pagopa-u-nodo-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
